/**
 * 生存战争网 - 信息仪表板页面语言配置
 * 包含仪表板页面的标题、区块、字段标签、状态提示的多语言翻译
 * 挂载到全局 window.DashboardLanguageConfig
 */
const DashboardLanguageConfig = {
    default: 'zh',
    supported: ['zh', 'en', 'ru', 'es'],

    names: {
        'zh': '🇨🇳 中文',
        'en': '🇺🇸 English',
        'ru': '🇷🇺 Русский',
        'es': '🇪🇸 Español'
    },

    storageKey: 'preferredLanguage',

    translations: {
        // 中文翻译
        zh: {
            page: {
                title: '信息仪表板 | 生存战争网',
                description: '信息仪表板 - 查看当前访问信息，包括 IP 地址、浏览器标识等',
                keywords: '信息仪表板,访问信息,IP地址,浏览器标识,User-Agent'
            },
            nav: { dashboard: '信息仪表板' },
            dashboard: {
                title: '📊 信息仪表板',
                subtitle: '以下是从您的本次访问中获取到的信息',
                updateTime: '最后更新时间：',
                refreshBtn: '🔄 刷新',
                // 区块标题
                sectionServer: '🌐 网络信息（服务器视角）',
                sectionBrowser: '🖥️ 浏览器信息',
                sectionSystem: '⚙️ 系统信息',
                sectionConnection: '📶 网络连接',
                sectionPage: '📄 页面信息',
                // 服务器视角字段
                f_ip: '您的 IP 地址',
                f_remoteAddr: '直连地址 (REMOTE_ADDR)',
                f_xForwardedFor: '代理链 (X-Forwarded-For)',
                f_xRealIp: '代理真实 IP (X-Real-IP)',
                f_serverUserAgent: '浏览器标识（服务器视角）',
                f_acceptLanguage: 'Accept-Language',
                f_acceptEncoding: 'Accept-Encoding',
                f_accept: 'Accept',
                f_referer: 'Referer 来源',
                f_requestMethod: '请求方法',
                f_requestUri: '请求地址',
                f_requestTime: '请求时间',
                f_serverName: '服务器名称',
                f_serverAddr: '服务器 IP',
                f_serverSoftware: '服务器软件',
                f_serverProtocol: 'HTTP 协议',
                f_https: 'HTTPS 加密',
                f_secChUa: 'Client Hints (UA)',
                f_secChUaPlatform: 'Client Hints (平台)',
                f_secChUaMobile: 'Client Hints (移动端)',
                // 浏览器字段
                f_userAgent: '浏览器标识 (User-Agent)',
                f_browser: '浏览器',
                f_browserVersion: '浏览器版本',
                f_renderEngine: '浏览器内核',
                f_language: '界面语言',
                f_languages: '可用语言',
                f_timezone: '时区',
                f_cookieEnabled: 'Cookie 已启用',
                f_online: '在线状态',
                f_doNotTrack: '禁止追踪 (Do Not Track)',
                f_webdriver: '自动化检测 (WebDriver)',
                f_pdfViewer: 'PDF 查看器',
                f_maxTouchPoints: '最大触控点数',
                // 系统字段
                f_platform: '操作系统平台',
                f_os: '操作系统',
                f_architecture: 'CPU 架构',
                f_bitness: '系统位数',
                f_cpuCores: 'CPU 逻辑核数',
                f_deviceMemory: '设备内存',
                f_screenSize: '屏幕分辨率',
                f_availScreen: '可用屏幕区域',
                f_colorDepth: '颜色深度',
                f_pixelDepth: '像素深度',
                f_devicePixelRatio: '设备像素比 (DPR)',
                f_viewport: '视口尺寸',
                f_orientation: '屏幕方向',
                f_windowPos: '窗口位置',
                f_windowSize: '窗口尺寸',
                // 网络连接字段
                f_effType: '网络类型 (Effective Type)',
                f_downlink: '估算下行速度',
                f_rtt: '估算往返延迟',
                f_saveData: '省流量模式',
                // 页面字段
                f_pageUrl: '当前页面 URL',
                f_pagePath: '页面路径',
                f_pageReferrer: '来源页面',
                f_loadTime: '页面加载耗时',
                f_domReady: 'DOM 就绪耗时',
                f_localTime: '本地时间',
                f_utcTime: 'UTC 时间',
                f_utcOffset: 'UTC 偏移',
                f_pageTitle: '页面标题',
                // 状态提示
                loading: '正在获取服务器视角信息…',
                serverUnavailable: '服务端信息暂不可用（需通过 PHP 部署方可获取真实 IP）',
                unknown: '未知',
                none: '无',
                yes: '是',
                no: '否',
                enabled: '已启用',
                disabled: '未启用',
                online: '在线',
                offline: '离线',
                gb: 'GB',
                mbps: 'Mbps',
                greeting: '👋 您好，来自 {ip} 的访客'
            }
        },

        // 英文翻译
        en: {
            page: {
                title: 'Dashboard | SurvivalCraft Web',
                description: 'Dashboard - view current visit information including IP address, browser identification, etc.',
                keywords: 'Dashboard,Visit Info,IP Address,User-Agent'
            },
            nav: { dashboard: 'Dashboard' },
            dashboard: {
                title: '📊 Dashboard',
                subtitle: 'The following information was collected from your visit',
                updateTime: 'Last updated: ',
                refreshBtn: '🔄 Refresh',
                sectionServer: '🌐 Network Info (Server View)',
                sectionBrowser: '🖥️ Browser Info',
                sectionSystem: '⚙️ System Info',
                sectionConnection: '📶 Network Connection',
                sectionPage: '📄 Page Info',
                f_ip: 'Your IP Address',
                f_remoteAddr: 'Direct Address (REMOTE_ADDR)',
                f_xForwardedFor: 'Proxy Chain (X-Forwarded-For)',
                f_xRealIp: 'Proxy Real IP (X-Real-IP)',
                f_serverUserAgent: 'User-Agent (Server View)',
                f_acceptLanguage: 'Accept-Language',
                f_acceptEncoding: 'Accept-Encoding',
                f_accept: 'Accept',
                f_referer: 'Referer',
                f_requestMethod: 'Request Method',
                f_requestUri: 'Request URI',
                f_requestTime: 'Request Time',
                f_serverName: 'Server Name',
                f_serverAddr: 'Server IP',
                f_serverSoftware: 'Server Software',
                f_serverProtocol: 'HTTP Protocol',
                f_https: 'HTTPS Encrypted',
                f_secChUa: 'Client Hints (UA)',
                f_secChUaPlatform: 'Client Hints (Platform)',
                f_secChUaMobile: 'Client Hints (Mobile)',
                f_userAgent: 'User-Agent',
                f_browser: 'Browser',
                f_browserVersion: 'Browser Version',
                f_renderEngine: 'Rendering Engine',
                f_language: 'UI Language',
                f_languages: 'Available Languages',
                f_timezone: 'Time Zone',
                f_cookieEnabled: 'Cookie Enabled',
                f_online: 'Online Status',
                f_doNotTrack: 'Do Not Track',
                f_webdriver: 'WebDriver',
                f_pdfViewer: 'PDF Viewer',
                f_maxTouchPoints: 'Max Touch Points',
                f_platform: 'OS Platform',
                f_os: 'Operating System',
                f_architecture: 'CPU Architecture',
                f_bitness: 'System Bitness',
                f_cpuCores: 'CPU Logical Cores',
                f_deviceMemory: 'Device Memory',
                f_screenSize: 'Screen Resolution',
                f_availScreen: 'Available Screen Area',
                f_colorDepth: 'Color Depth',
                f_pixelDepth: 'Pixel Depth',
                f_devicePixelRatio: 'Device Pixel Ratio',
                f_viewport: 'Viewport Size',
                f_orientation: 'Screen Orientation',
                f_windowPos: 'Window Position',
                f_windowSize: 'Window Size',
                f_effType: 'Effective Network Type',
                f_downlink: 'Estimated Downlink',
                f_rtt: 'Estimated RTT',
                f_saveData: 'Data Saver',
                f_pageUrl: 'Current Page URL',
                f_pagePath: 'Page Path',
                f_pageReferrer: 'Referrer',
                f_loadTime: 'Page Load Time',
                f_domReady: 'DOM Ready Time',
                f_localTime: 'Local Time',
                f_utcTime: 'UTC Time',
                f_utcOffset: 'UTC Offset',
                f_pageTitle: 'Page Title',
                loading: 'Fetching server-side info…',
                serverUnavailable: 'Server-side info unavailable (requires PHP deployment to get the real IP)',
                unknown: 'Unknown',
                none: 'None',
                yes: 'Yes',
                no: 'No',
                enabled: 'Enabled',
                disabled: 'Disabled',
                online: 'Online',
                offline: 'Offline',
                gb: 'GB',
                mbps: 'Mbps',
                greeting: '👋 Hello, visitor from {ip}'
            }
        },

        // 俄语翻译
        ru: {
            page: {
                title: 'Панель информации | SurvivalCraft Web',
                description: 'Панель информации - просмотр текущей информации о посещении, включая IP-адрес, идентификацию браузера и т.д.',
                keywords: 'Панель информации,Информация о посещении,IP-адрес,User-Agent'
            },
            nav: { dashboard: 'Панель информации' },
            dashboard: {
                title: '📊 Панель информации',
                subtitle: 'Ниже приведена информация, полученная из вашего посещения',
                updateTime: 'Последнее обновление: ',
                refreshBtn: '🔄 Обновить',
                sectionServer: '🌐 Сетевая информация (вид сервера)',
                sectionBrowser: '🖥️ Информация о браузере',
                sectionSystem: '⚙️ Информация о системе',
                sectionConnection: '📶 Сетевое подключение',
                sectionPage: '📄 Информация о странице',
                f_ip: 'Ваш IP-адрес',
                f_remoteAddr: 'Прямой адрес (REMOTE_ADDR)',
                f_xForwardedFor: 'Цепочка прокси (X-Forwarded-For)',
                f_xRealIp: 'Реальный IP прокси (X-Real-IP)',
                f_serverUserAgent: 'User-Agent (вид сервера)',
                f_acceptLanguage: 'Accept-Language',
                f_acceptEncoding: 'Accept-Encoding',
                f_accept: 'Accept',
                f_referer: 'Источник (Referer)',
                f_requestMethod: 'Метод запроса',
                f_requestUri: 'URI запроса',
                f_requestTime: 'Время запроса',
                f_serverName: 'Имя сервера',
                f_serverAddr: 'IP сервера',
                f_serverSoftware: 'ПО сервера',
                f_serverProtocol: 'HTTP-протокол',
                f_https: 'HTTPS шифрование',
                f_secChUa: 'Client Hints (UA)',
                f_secChUaPlatform: 'Client Hints (платформа)',
                f_secChUaMobile: 'Client Hints (мобильный)',
                f_userAgent: 'Идентификация браузера (User-Agent)',
                f_browser: 'Браузер',
                f_browserVersion: 'Версия браузера',
                f_renderEngine: 'Движок браузера',
                f_language: 'Язык интерфейса',
                f_languages: 'Доступные языки',
                f_timezone: 'Часовой пояс',
                f_cookieEnabled: 'Cookie включены',
                f_online: 'Статус подключения',
                f_doNotTrack: 'Do Not Track',
                f_webdriver: 'WebDriver',
                f_pdfViewer: 'PDF-просмотрщик',
                f_maxTouchPoints: 'Макс. точек касания',
                f_platform: 'Платформа ОС',
                f_os: 'Операционная система',
                f_architecture: 'Архитектура CPU',
                f_bitness: 'Разрядность системы',
                f_cpuCores: 'Логические ядра CPU',
                f_deviceMemory: 'Память устройства',
                f_screenSize: 'Разрешение экрана',
                f_availScreen: 'Доступная область экрана',
                f_colorDepth: 'Глубина цвета',
                f_pixelDepth: 'Глубина пикселей',
                f_devicePixelRatio: 'Соотношение пикселей (DPR)',
                f_viewport: 'Размер окна просмотра',
                f_orientation: 'Ориентация экрана',
                f_windowPos: 'Позиция окна',
                f_windowSize: 'Размер окна',
                f_effType: 'Эффективный тип сети',
                f_downlink: 'Оценка скорости загрузки',
                f_rtt: 'Оценка задержки (RTT)',
                f_saveData: 'Экономия трафика',
                f_pageUrl: 'URL текущей страницы',
                f_pagePath: 'Путь страницы',
                f_pageReferrer: 'Источник (Referrer)',
                f_loadTime: 'Время загрузки страницы',
                f_domReady: 'Время готовности DOM',
                f_localTime: 'Локальное время',
                f_utcTime: 'Время UTC',
                f_utcOffset: 'Смещение UTC',
                f_pageTitle: 'Заголовок страницы',
                loading: 'Получение информации с сервера…',
                serverUnavailable: 'Информация сервера недоступна (требуется развертывание PHP для получения реального IP)',
                unknown: 'Неизвестно',
                none: 'Нет',
                yes: 'Да',
                no: 'Нет',
                enabled: 'Включено',
                disabled: 'Отключено',
                online: 'Онлайн',
                offline: 'Офлайн',
                gb: 'ГБ',
                mbps: 'Мбит/с',
                greeting: '👋 Здравствуйте, гость из {ip}'
            }
        },

        // 西班牙语翻译
        es: {
            page: {
                title: 'Panel de Información | SurvivalCraft Web',
                description: 'Panel de información - vea la información actual de la visita, incluida la dirección IP, la identificación del navegador, etc.',
                keywords: 'Panel de Información,Información de Visita,Dirección IP,User-Agent'
            },
            nav: { dashboard: 'Panel de Información' },
            dashboard: {
                title: '📊 Panel de Información',
                subtitle: 'La siguiente información se obtuvo de su visita',
                updateTime: 'Última actualización: ',
                refreshBtn: '🔄 Actualizar',
                sectionServer: '🌐 Info de Red (Vista del Servidor)',
                sectionBrowser: '🖥️ Info del Navegador',
                sectionSystem: '⚙️ Info del Sistema',
                sectionConnection: '📶 Conexión de Red',
                sectionPage: '📄 Info de la Página',
                f_ip: 'Su dirección IP',
                f_remoteAddr: 'Dirección directa (REMOTE_ADDR)',
                f_xForwardedFor: 'Cadena de proxy (X-Forwarded-For)',
                f_xRealIp: 'IP real del proxy (X-Real-IP)',
                f_serverUserAgent: 'User-Agent (Vista del Servidor)',
                f_acceptLanguage: 'Accept-Language',
                f_acceptEncoding: 'Accept-Encoding',
                f_accept: 'Accept',
                f_referer: 'Referer',
                f_requestMethod: 'Método de solicitud',
                f_requestUri: 'URI de solicitud',
                f_requestTime: 'Hora de solicitud',
                f_serverName: 'Nombre del servidor',
                f_serverAddr: 'IP del servidor',
                f_serverSoftware: 'Software del servidor',
                f_serverProtocol: 'Protocolo HTTP',
                f_https: 'Cifrado HTTPS',
                f_secChUa: 'Client Hints (UA)',
                f_secChUaPlatform: 'Client Hints (Plataforma)',
                f_secChUaMobile: 'Client Hints (Móvil)',
                f_userAgent: 'Identificación del navegador (User-Agent)',
                f_browser: 'Navegador',
                f_browserVersion: 'Versión del navegador',
                f_renderEngine: 'Motor de renderizado',
                f_language: 'Idioma de la interfaz',
                f_languages: 'Idiomas disponibles',
                f_timezone: 'Zona horaria',
                f_cookieEnabled: 'Cookies habilitadas',
                f_online: 'Estado en línea',
                f_doNotTrack: 'No rastrear (DNT)',
                f_webdriver: 'WebDriver',
                f_pdfViewer: 'Visor de PDF',
                f_maxTouchPoints: 'Máx. puntos táctiles',
                f_platform: 'Plataforma del SO',
                f_os: 'Sistema operativo',
                f_architecture: 'Arquitectura de CPU',
                f_bitness: 'Bits del sistema',
                f_cpuCores: 'Núcleos lógicos de CPU',
                f_deviceMemory: 'Memoria del dispositivo',
                f_screenSize: 'Resolución de pantalla',
                f_availScreen: 'Área de pantalla disponible',
                f_colorDepth: 'Profundidad de color',
                f_pixelDepth: 'Profundidad de píxeles',
                f_devicePixelRatio: 'Relación de píxeles (DPR)',
                f_viewport: 'Tamaño de la ventana gráfica',
                f_orientation: 'Orientación de pantalla',
                f_windowPos: 'Posición de la ventana',
                f_windowSize: 'Tamaño de la ventana',
                f_effType: 'Tipo de red efectivo',
                f_downlink: 'Velocidad de descarga estimada',
                f_rtt: 'Latencia estimada (RTT)',
                f_saveData: 'Ahorro de datos',
                f_pageUrl: 'URL de la página actual',
                f_pagePath: 'Ruta de la página',
                f_pageReferrer: 'Referrer',
                f_loadTime: 'Tiempo de carga de la página',
                f_domReady: 'Tiempo de preparación DOM',
                f_localTime: 'Hora local',
                f_utcTime: 'Hora UTC',
                f_utcOffset: 'Desplazamiento UTC',
                f_pageTitle: 'Título de la página',
                loading: 'Obteniendo información del servidor…',
                serverUnavailable: 'Información del servidor no disponible (requiere implementación PHP para obtener la IP real)',
                unknown: 'Desconocido',
                none: 'Ninguno',
                yes: 'Sí',
                no: 'No',
                enabled: 'Habilitado',
                disabled: 'Deshabilitado',
                online: 'En línea',
                offline: 'Desconectado',
                gb: 'GB',
                mbps: 'Mbps',
                greeting: '👋 Hola, visitante de {ip}'
            }
        }
    }
};

window.DashboardLanguageConfig = DashboardLanguageConfig;
